### ISSUE TITLE
MongoDB Specific Features

### ISSUE THREAD

**Issue by Brendonovich** [Brendonovich/prisma-client-rust#128]
- [x] aggregateRaw
- [x] findRaw
- [x] runCommandRaw
- [x] [Composite Types](https://github.com/Brendonovich/prisma-client-rust/issues/82)
- [ ] TBD

**Comment by Zizico2** [comment]
Can I be of help? I need this asap. If you could just point me in the sort of general direction

**Comment by Brendonovich** [comment]
If you really want to try then work off the `0.6.0` branch, implement appropriate code generation in the generator in the `cli` crate, and add the queries in the main library. I'm not willing to elaborate further since most of PCR's code is not very external collaborator-friendly and I'd rather implement features myself for now

**Comment by Zizico2** [comment]
I guess I can add one more. Is what's the status on `[composite types](https://www.prisma.io/docs/concepts/components/prisma-client/composite-types)`?

**Comment by Brendonovich** [comment]
@Zizico2 I won't be working on it for a while, MongoDB isn't a priority at Spacedrive and after 0.6.0 is released I'll need to take some time away from PCR.

**Comment by Zizico2** [comment]
I'm gonna be working on this soon. I just wanted to know if any work had been done in this direction so I wouldn't be doing unnecessary work. I'm fairly confident I can implement the 4 points. I'm getting everything working with PCR as-is at my company, and will implement the MongoDB specific stuff after. Even if you don't end up agreeing with some of my choices it should serve as a foundation

**Comment by Zizico2** [comment]
Another thing I bumped into that may be worth a new issue since it isn't mongo only, necessarily. Would it make sense to have an API that instead of returning a `Vec<Data>`, returns a `Stream<Item = Data>`? The `mongo` driver allows streaming the response's records 1 by 1. And other DB's drivers allow the same I assume. And even if they don't, you can always fallback to the eager implementation and just have the `Stream` behave like an `Iterator`. 

(btw, if it seems like I'm poking a lot of holes it's because I really enjoy using PCR, and I just want to see it thrive c: (and be the best it can be for mongo, which is my use case))

**Comment by Brendonovich** [comment]
For now I only want to include APIs that already exist in Prisma Client JS, like the ones listed. Streaming is currently not supported by Prisma (https://github.com/prisma/prisma/issues/5055), and would require significant work to implement here. I'm open to it, but it definitely isn't a priority.

**Comment by Brendonovich** [comment]
Raw query docs: https://prisma-client-rust-git-main-brendonovich.vercel.app/extra/raw#aggregate_raw
