### ISSUE TITLE
Reason about Brendonovich/prisma-engines (fork) dependency

### ISSUE THREAD

**Issue by vincent-herlemont** [Brendonovich/prisma-client-rust#148]
NOTE: I try to understand in more detail the motivations around forking the official repo.

I see [here  Cargo.toml#L31-L37](https://github.com/Brendonovich/prisma-client-rust/blob/57d154b5d897510905ab8a605d4fae79f5372b56/Cargo.toml#L31-L37) that a [fork](https://github.com/Brendonovich/prisma-engines) of [prisma/prisma-engines](https://github.com/prisma/prisma-engines) is used.

Here are some questions about that:
- What are the reasons that led to this fork?
- Aren't you afraid it will be hard to maintain if there are changes on the official repo that conflict with your updates? 

There is another project [polytope-labs/prisma-client-rs](https://github.com/polytope-labs/prisma-client-rs) that uses the official repo, did you have some input on it?

**Comment by Brendonovich** [comment]
There are a few reasons, but the one that makes it entirely necessary is dependency versioning. The engines contain a lot of dependencies sourced from GitHub that aren't locked to specific commits, instead they point to the main branch or some other branch. For example, `quaint` is a crate maintained by Prisma but is not locked to a specific version. This works for Prisma since they know what they're doing, but for Prisma Client Rust we're usually behind by a few versions. I really don't want breaking changes to `quaint` stopping the engines from compiling just because the engines version being used is older - I'm pretty sure if I hadn't locked the version of `quaint` this issue would have already happened.
Additionally, features like `sqlite-create-many` are only possible because of modifications I've made to the engines.
Yes I'm afraid of making too many changes such that it would be hard to merge updates, but I'm willing to put in the work to make sure Prisma Client Rust is stable and has plenty of features.

**Comment by vincent-herlemont** [comment]
Thank you for your answer @Brendonovich .

Why didn't you submit your changes directly to the official repository?

Do you plan to do this?

**Comment by Brendonovich** [comment]
I'd love for my changes to be merged upstream, but the Prisma team are focused on the needs of the JS client. I've spoken with Prisma and tried to merge some changes, but they just aren't interested.
Plus even if they did accept the changes the repo would still be a way larger download size.
