### ISSUE TITLE
Unable to check if an optional relation is null

### ISSUE THREAD

**Issue by jqphu** [Brendonovich/prisma-client-rust#214]
Following from discord.

Given an optional relation 

```
model User {

profile Profile?

}
```

It would be nice to filter on this field e.g. get all the users that don't have a profile.

**Comment by Brendonovich** [comment]
Not sure if this is a me problem or if the filters from Prisma don't allow a method to do this but I'll check it out

**Comment by jqphu** [comment]
Here's a snippet of something similar on typescript.

```
  const users = await prisma.user.findMany({
    where: {
      NOT: [
        {
          referredBy: null,
        }
      ],
      AND: [
        {
          referredOneMonthTrialExpiryDate: null,
        }
      ]
    }
  });
```

Finding all the users where the referredBy is not null, but the referredOneMonthTrialExpiryDate is null.

ReferredBy in this case is a relation, referredOneMonthTrialExpiryDate is just a simple DateTime.

Hope that's somewhat helpful.

**Comment by Brendonovich** [comment]
I've thought about it, and I think I'll need to custom-implement this operation myself. The example you provided is basically `user::referred_by::equals(None)` - but I don't provide an `equals` function for relations, and I don't plan on it since it _only_ makes sense for null relations.
Instead I'm thinking of adding an `is_null` filter which does the same thing. It'd look like `user::referred_by::is_null()`.

**Comment by jqphu** [comment]
That makes sense!

Thanks @Brendonovich :).
