### ISSUE TITLE
Data structs don't derive PartialEq

### ISSUE THREAD

**Issue by liamwh** [Brendonovich/prisma-client-rust#280]
It would be fantastic if structs could derive PartialEq if possible for those structs

https://youtu.be/Nzclc6MswaI

**Comment by Brendonovich** [comment]
I'm not sure I want to do this - especially since two records could be equal but have different relations fetched on them, making the `derive(PartialEq)` think they're equal. Manually implementing it to only compare relations if they have been fetched for both models could work?
Still not sure I'm onboard though - Comparing entire db rows for equality seems kinda ill-advised and isn't something that [diesel](https://docs.rs/diesel/latest/diesel/sql_types/index.html) or [sqlx](https://docs.rs/sqlx/latest/sqlx/sqlite/struct.SqliteValue.html) support with their types.

**Comment by Brendonovich** [comment]
Not going to implement this
