### ISSUE TITLE
Suppress rust warnings from outputted `prisma.rs`

### ISSUE THREAD

**Issue by dukeeagle** [Brendonovich/prisma-client-rust#331]
Awesome work here! Would it be possible to prevent add an `#![allow(warnings)]` to the top of `prisma.rs` in order to avoid unnecessary rust compiler warnings such as:

```
warning: function `equals` is never used
    --> src/prisma.rs:5438:16
     |
5438 |         pub fn equals(value: i32) -> WhereParam {
     |                ^^^^^^
```

**Comment by Brendonovich** [comment]
This used to be done but was removed because of #306. [The docs](https://prisma.brendonovich.dev/getting-started/setup#creating-the-client) now recommend to do this:
<img width="666" alt="image" src="https://user-images.githubusercontent.com/14191578/237051392-ec821c8f-8639-460a-9223-7c76d738fa62.png">
