### ISSUE TITLE
Interactive Transactions

### ISSUE THREAD

**Issue by tingfeng-key** [Brendonovich/prisma-client-rust#60]
support transaction

**Comment by Brendonovich** [comment]
I do plan on supporting transactions, but they're not a priority right now

**Comment by lostfictions** [comment]
> Interactive transactions are still a preview feature so I'm not going to do them yet.

Interactive transactions have been [GA in Prisma since 4.7.0](https://github.com/prisma/prisma/releases/tag/4.7.0), incidentally!

**Comment by Brendonovich** [comment]
Ok so here's the API I've got at the moment.

<img width="772" alt="image" src="https://user-images.githubusercontent.com/14191578/211133602-b324f3bc-ad8a-488a-b15a-42ef67c1d803.png">

Transactions can be done in two ways. Both are able to commit and rollback, and provide a dedicated instance of `PrismaClient` that keeps track of the transaction id.

## Closure

`client._transaction().run(...)` allows writing the whole transaction inside a closure. This mirrors the JS client's API and provides an intuitive sense for whether the transaction will commit or rollback. The closure must return a `Result`. If `Ok()`  is returned, the transaction will be committed. If `Err()` is returned (either at the end of the closure or via `?`), the transaction will be rolled back.

The first (and only) argument of the closure is the transaction-unique instance of `PrismaClient`, which must be moved into the async block via `async move`.

The biggest issue I see with this method is how obtuse error handling can be. There's two options for what the error type could be:
1. `QueryError` only: This is nice because every closure can abide by this restriction quite easily, with no need to provide an error type. This also sucks because it means you can't use your own error types, so I likely won't use it.
2. `From<QueryError>` (current): This is nice because you can use either `QueryError` or your own error type that implements `From<QueryError>` (easy with `thiserror`), but the ergonomics are clunky if you don't know what you're doing. Even if your closure just returns `Ok(())` you'll get an error since it won't be able to figure out what return type the `Result` should have. In practice this isn't as big of an issue, since if you're making a transaction it's likely that the final thing done inside the closure is a query, so you can just return `.exec().await` which will allow inferring of both the `Ok` and `Err` types. If you want to manipulate the result further just use `.map`.

```rust
let (user, post) = client
    ._transaction()
    .run(|client| async move {
        let user = client
            .user()
            .create("brendan".to_string(), vec![])
            .exec()
            .await?;
            
        client
            .post()
            .create(
                "test".to_string(),
                true,
                vec![post::author::connect(user::id::equals(user.id.clone()))],
            )
            .exec()
             // no ? to provide closure with concrete Err type
            .await
            .map(|post| (user, post))
    })
    .await?;
```

## Begin/Commit/Rollback

If closures aren't your style then an imperative system is also available. `client._transaction.begin()` will return (TransactionController, PrismaClient), allowing for manual control of when the transaction is committed or rolled back. The returned `PrismaClient` holds on to the transaction ID.

When the transaction should end, `TransactionController::commit` or `TransactionController::rollback` can be used. Both of these consume a `PrismaClient` not only to end the transaction, but also to ensure that the transaction-specific client is not used outside of the transaction.

This method seems pretty sound to me, the only problem I can think of is if `?` is used for error handling then `commit` or `rollback` will never be called, leaving the transaction open for longer than it needs to be before timing out and rolling back.

**Comment by lostfictions** [comment]
Thanks for the update! That sounds great to me.

> `From<QueryError>` (current): This is nice because you can use either `QueryError` or your own error type that implements `From<QueryError>`

This mean's it'd work out of the box with `anyhow` too, right...? I haven't been using Rust in earnest for very long, but I have struggled a bit with the ergonomics of error handling (primarily around the verboseness the orphan rule seems to cause -- most recently for me in rspc procedures).

As for imperative transactions, it sort of feels to me like they should be discouraged in the api (exposed less prominently than `run()`, say) and users should be nudged towards the closure-based approach instead, unless they have some _really_ good reason to reach for them. (To be honest I can't think of any such good reason offhand, but maybe there's a few cases where that particular level of control could be justified.)

> This method seems pretty sound to me, the only problem I can think of is if `?` is used for error handling then `commit` or `rollback` will never be called, leaving the transaction open for longer than it needs to be before timing out and rolling back.

What about implementing `Drop` for the transaction client? Which I guess could... trace a warning and roll back immediately?

**Comment by Brendonovich** [comment]
> This mean's it'd work out of the box with anyhow too, right...?

I haven't got much experience with `anyhow`, but `QueryError` implements `std::error::Error` so it should be fine. You'd just have to make sure the closure's error type is hinted to be `anyhow::Error`.

>  As for imperative transactions, it sort of feels to me like they should be discouraged in the api

I don't think they should be discouraged, seeing as [SeaORM](https://www.sea-ql.org/SeaORM/docs/advanced-query/transaction/) are loud and proud about their procedural transactions, but I think that people will naturally gravitate to closures seeing as the wrappers you need around `begin/commit/rollback` end up looking [very similar](https://prisma-client-rust-nar8fniaa-brendonovich.vercel.app/extra/transactions#procedural-transactions) to closures anyway.

> What about implementing Drop for the transaction client?

Apart from the issues you identified, `Drop` has to be synchronous so this wouldn't be possible anyway.

> it sort of feels like these two things should be fused into some specialization of `PrismaClient` with transaction awareness...?

I'd really like to avoid generating multiple `PrismaClient` structs. It's extra codegen, and means that if a function wants to accept a client as an argument, it is locked to one type. It would also take the `commit/rollback` functions out of the core, which I don't really want to do. That does give me the idea to use `Deref` to mimic inheritance and wrap the regular client in something that provides transaction capabilities, but that's kinda frowned upon in the Rust world.
Procedural transactions having a slightly weird api can be a deterrent against using them in favour of closures anyway.

**Comment by niklaskorz** [comment]
`Drop` being synchronous was worked around in SeaORM by enqueuing the rollback and executing it during the next async operation: <https://github.com/SeaQL/sea-orm/blob/2a713b06cd9c0ef2e8b15c40917cb9a2afcbb27b/src/database/transaction.rs#L285>

If this is not viable here, dropping a transaction that has been neither comitted nor rolled back should panic to raise awareness.
