### ISSUE TITLE
Unique multi-column constraint

### ISSUE THREAD

**Issue by John0x** [Brendonovich/prisma-client-rust#62]
Hey, I'm not sure if this behaviour is intended, but it seems quite cumbersome to me.

Let's say we have the schema:
```prisma
model Category {
  id       Int       @id @default(autoincrement())
  name     String
  parent   Category? @relation("CategoryChildren", fields: [parentId], references: [id])
  parentId Int?

  children Category[]             @relation("CategoryChildren")
  programs CategoriesOnPrograms[]

  @@unique([name, parentId])
}
```

The generated UniqueParams are:
```rust
    pub enum UniqueWhereParam {
        NameParentIdEquals(String, i32),
        IdEquals(i32),
    }
```

But shouldn't it be the following, since the parent is optional?:
```rust
    pub enum UniqueWhereParam {
        NameParentIdEquals(String,Option<i32>),
        IdEquals(i32),
    }
```

**Comment by Brendonovich** [comment]
Though it may seem cumbersome, this is intentional. `NULL` in SQL is not unique - ie `NULL != NULL` - and so you could have multiple `Category` rows where `parentId` is `NULL` but `name` is the same. Thus, a `UniqueWhereParam` should not allow for `NULL`, since it could return multiple rows. See more here: https://github.com/prisma/prisma/issues/3772

**Comment by John0x** [comment]
Huh, wasn't aware of that. Thanks for the clarification :)
