### ISSUE TITLE
Run migrations programatically

### ISSUE THREAD

**Issue by Suyashtnt** [Brendonovich/prisma-client-rust#78]
This is the best way to fix the issues that spacedive and other desktop apps would have: running migrations. If it could be done programmatically it would fix the issues

**Comment by Brendonovich** [comment]
It's probably possible to use the migration engine directly, but I'm not going to look into it at the moment. Prisma Client Rust wouldn't be required to do so though, so feel free to try it yourself.
For Spacedrive we wrote a custom migration runner that embeds the migrations inside the binary, and then use custom queries to run them. Currently, I'm not interested in trying to do more since it works well enough.

**Comment by Brendonovich** [comment]
Possibly, I'm not considering it at the moment though. If someone does want to do so then technically you could just read the SQL and execute it as a raw query and let that be the end of it, but it's best to do some validation too, though I'm not the person to ask about how to do that haha

**Comment by tbillington** [comment]
@Suyashtnt if you'd like to implement this in your code you can see the source of the sqlx migrator https://docs.rs/sqlx/latest/sqlx/migrate/struct.Migrator.html.
