### ISSUE TITLE
Bunch of outdated dependencies.

### ISSUE THREAD

**Issue by Suyashtnt** [Brendonovich/prisma-client-rust#79]
After I added prisma-client-rust to my project, it instantly gained around 25 security issues due to outdated and insecure dependencies, coming from your prisma-* forks. Is there any work on updating those forks to remove some of the outdated deps?

Repo: https://github.com/glowsquid-launcher/glowsquid/security/dependabot

**Comment by Brendonovich** [comment]
I could do that, though I'd rather use the same dependency versions as regular Prisma. Updating the forks to have locked git dependencies is a hassle enough.
Those outdated dependencies are the same ones being used by every Prisma user though, not just Prisma Client Rust, so I'm comfortable placing the burden of upgrading on Prisma rather than myself.
